### ISSUE TITLE
Allow users to supply their own test data

### ISSUE THREAD

**Issue by eloquenza** [eloquenza/theme_boost_union_test_envs#18]
As a tester,
I might want to use another set of test data,
because I want to test specific plugins that need a different setup,
or because it better models the way a specific university set ups their moodles.

Currently, we use the wonderful [moodle-datagenerator](https://github.com/andrewnicols/moodle-datagenerator) to offer newly created Moodle test containers with a specific set of test data.
This allows our testers to have a similar feel for each Moodle test container and allow themselves the get into their own work flow w.r.t to manual testing.

An implementation for this could look like this:

1. User defines test-data in a readable format, i.e. a YAML file looking like this:
```
users:
  testuser1: ...
  testuser2: ...
courses:
  testcourse1: ...
  testcourse2: ...
cohorts:
  testcohort1: ...
categories:
  testcategory1: ...
badges:
  badge1: ...
```
2. User explains for which container the test data should be used:
```./boost-union build boost-union-latest 4.3.0 --testdata my-new-testdata.yml```
3. Our application uses either direct DB manipulation or a script like MooSH to implement how the test data will be added to said Moodle test container.
